# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoAppPinterest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoAppPinterest
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 6.0'
  pod 'SwiftyGif'

end
